# Generated by Django 6.1 on 2026-08-10 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=250)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('apply_link', models.URLField(max_length=500)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated skill tags', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='RemoteOK', max_length=100)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-posted_date', '-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='BookmarkedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_jobs', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
