# Generated by Django 6.0.7 on 2026-08-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
    ]
